# Generated by Django 4.0.5 on 2022-06-09 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_record',
            name='id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='student_record',
            name='student_no',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.student'),
        ),
        migrations.AlterField(
            model_name='user',
            name='student_no',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.student'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_name',
            field=models.CharField(default=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.student'), max_length=20, unique=True),
        ),
    ]
